# Subword tokenizers

## Setup

In [14]:
!pip install -q -U tensorflow-text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 23.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-gbq 0.19.2 requires google-auth-oauthlib>=0.7.0, but you have google-auth-oauthlib 0.4.6 which is incompatible.
tensorflow-metadata 1.15.0 requires protobuf<4.21,>=3.20.3; python_version < "3.11", but you have protobuf 4.25.3 which is incompatible.


In [2]:
!unzip /content/koumankan_mt_dyu_fr_tfds.zip

Archive:  /content/koumankan_mt_dyu_fr_tfds.zip
   creating: koumankan_mt_dyu_fr_tfds/
  inflating: koumankan_mt_dyu_fr_tfds/koumankan_mt_dyu_fr_tfds_dataset_builder.py  
  inflating: koumankan_mt_dyu_fr_tfds/koumankan_mt_dyu_fr_tfds_dataset_builder_test.py  
  inflating: koumankan_mt_dyu_fr_tfds/README.md  
  inflating: koumankan_mt_dyu_fr_tfds/CITATIONS.bib  
  inflating: koumankan_mt_dyu_fr_tfds/TAGS.txt  
  inflating: koumankan_mt_dyu_fr_tfds/__init__.py  
  inflating: koumankan_mt_dyu_fr_tfds/checksums.tsv  
   creating: koumankan_mt_dyu_fr_tfds/data/
  inflating: koumankan_mt_dyu_fr_tfds/data/train_refined.csv  
  inflating: koumankan_mt_dyu_fr_tfds/data/val_refined.csv  
  inflating: koumankan_mt_dyu_fr_tfds/data/test_refined.csv  
   creating: koumankan_mt_dyu_fr_tfds/dummy_data/


In [3]:
!pip install -q tfds-nightly tensorflow matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 58.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.3/309.3 kB 39.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 MB 1.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 102.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 95.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 37.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 100.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 70.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 38.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 104.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 69.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This b

In [5]:
!pip install -q apache-beam

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.5/14.5 MB 60.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.7/89.7 kB 13.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.0/145.0 kB 20.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.0/152.0 kB 25.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 92.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 6.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 53.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.1/252.1 kB 26.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 61.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 60.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.p

In [7]:
!pip install -q mlcroissant

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 33.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 4.2 MB/s eta 0:00:00


In [8]:
!tfds --version

TensorFlow Datasets: 4.9.6+nightly


In [9]:
!cd /content/koumankan_mt_dyu_fr_tfds && tfds build

INFO[build.py]: Loading dataset  from path: /content/koumankan_mt_dyu_fr_tfds/koumankan_mt_dyu_fr_tfds_dataset_builder.py
2024-07-02 12:38:32.065218: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-02 12:38:32.090438: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-02 12:38:32.090490: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-02 12:38:32.106130: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in othe

In [10]:
!pip install -q tensorflow_datasets

In [15]:
import collections
import os
import pathlib
import re
import string
import sys
import tempfile
import time

import numpy as np
import matplotlib.pyplot as plt

import tensorflow_datasets as tfds
import tensorflow_text as text
import tensorflow as tf

In [16]:
tf.get_logger().setLevel('ERROR')
pwd = pathlib.Path.cwd()

## Load the dataset

In [17]:
examples, metadata = tfds.load('koumankan_mt_dyu_fr_tfds', with_info=True,
                               as_supervised=True)
train_examples, val_examples = examples['train'], examples['validation']

This dataset produces Dyula/French sentence pairs:

In [20]:
for dyu, fr in train_examples.take(2):
  print("Dyula: ", dyu.numpy().decode('utf-8'))
  print("French:   ", fr.numpy().decode('utf-8'))

Dyula:  ayi accident kè a ma mè
French:    elle a eu un accident de la route la semaine dernière
Dyula:  gèma alé ni kefé ni nonnon
French:    blanc comme du café au lait


Note a few things about the example sentences above:
* They're lower case.
* There are spaces around the punctuation.
* It's not clear if or what unicode normalization is being used.

In [21]:
train_fr = train_examples.map(lambda dyu, fr: fr)
train_dyu = train_examples.map(lambda dyu, fr: dyu)

## Generate the vocabulary

In [24]:
from tensorflow_text.tools.wordpiece_vocab import bert_vocab_from_dataset as bert_vocab

The `bert_vocab.bert_vocab_from_dataset` function will generate the vocabulary.

There are many arguments you can set to adjust its behavior. For this tutorial, you'll mostly use the defaults. If you want to learn more about the options, first read about [the algorithm](#algorithm), and then have a look at [the code](https://github.com/tensorflow/text/blob/master/tensorflow_text/tools/wordpiece_vocab/bert_vocab_from_dataset.py).


In [25]:
bert_tokenizer_params=dict(lower_case=True)
reserved_tokens=["[PAD]", "[UNK]", "[START]", "[END]"]

bert_vocab_args = dict(
    # The target vocabulary size
    vocab_size = 8000,
    # Reserved tokens that must be included in the vocabulary
    reserved_tokens=reserved_tokens,
    # Arguments for `text.BertTokenizer`
    bert_tokenizer_params=bert_tokenizer_params,
    # Arguments for `wordpiece_vocab.wordpiece_tokenizer_learner_lib.learn`
    learn_params={},
)

In [26]:
%%time
dyu_vocab = bert_vocab.bert_vocab_from_dataset(
    train_dyu.batch(1000).prefetch(2),
    **bert_vocab_args
)

CPU times: user 10.7 s, sys: 269 ms, total: 11 s
Wall time: 10.8 s


Here are some slices of the resulting vocabulary.

In [27]:
print(dyu_vocab[:10])
print(dyu_vocab[100:110])
print(dyu_vocab[1000:1010])
print(dyu_vocab[-10:])

['[PAD]', '[UNK]', '[START]', '[END]', "'", '0', '1', 'a', 'b', 'c']
['##man', 'kalan', '##o', 'bara', '##t', 'kuma', 'yan', 'taga', 'nunu', 'ya']
[]
['ɲanama', 'ɲɛn', "##'", '##0', '##1', '##j', '##q', '##v', '##x', '##ŋ']


Write a vocabulary file:

In [28]:
def write_vocab_file(filepath, vocab):
  with open(filepath, 'w') as f:
    for token in vocab:
      print(token, file=f)

In [29]:
write_vocab_file('dyu_vocab.txt', dyu_vocab)

Use that function to generate a vocabulary from the french data:

In [30]:
%%time
fr_vocab = bert_vocab.bert_vocab_from_dataset(
    train_fr.batch(1000).prefetch(2),
    **bert_vocab_args
)


CPU times: user 15.8 s, sys: 146 ms, total: 15.9 s
Wall time: 16.7 s


In [31]:
print(fr_vocab[:10])
print(fr_vocab[100:110])
print(fr_vocab[1000:1010])
print(fr_vocab[-10:])

['[PAD]', '[UNK]', '[START]', '[END]', "'", '.', 'a', 'b', 'c', 'd']
['par', '##on', '##n', '##te', 'avez', 'avec', 'lui', 'trois', 'sa', 'moi']
['attendre', 'aurais', 'autrefois', 'avaient', 'besoin', 'breton', 'but', 'cafe', 'capitaine', 'danser']
['##ł', '##œ', '##ʻ', '##α', '##–', '##—', '##’', '##“', '##”', '##€']


Here are the two vocabulary files:

In [32]:
write_vocab_file('fr_vocab.txt', fr_vocab)

In [33]:
!ls *.txt

dyu_vocab.txt  fr_vocab.txt


## Build the tokenizer
<a id="build_the_tokenizer"></a>

The `text.BertTokenizer` can be initialized by passing the vocabulary file's path as the first argument (see the section on [tf.lookup](#tf.lookup) for other options):

In [34]:
dyu_tokenizer = text.BertTokenizer('dyu_vocab.txt', **bert_tokenizer_params)
fr_tokenizer = text.BertTokenizer('fr_vocab.txt', **bert_tokenizer_params)

Now you can use it to encode some text. Take a batch of 3 examples from the english data:

In [35]:
for dyu_examples, fr_examples in train_examples.batch(3).take(1):
  for ex in fr_examples:
    print(ex.numpy())

b'elle a eu un accident de la route la semaine derni\xc3\xa8re'
b'blanc comme du caf\xc3\xa9 au lait'
b'la baffe  \xc3\xa7a humilie'


Run it through the `BertTokenizer.tokenize` method. Initially, this returns a `tf.RaggedTensor` with axes `(batch, word, word-piece)`:

In [36]:
# Tokenize the examples -> (batch, word, word-piece)
token_batch = fr_tokenizer.tokenize(fr_examples)
# Merge the word and word-piece axes -> (batch, tokens)
token_batch = token_batch.merge_dims(-2,-1)

for ex in token_batch.to_list():
  print(ex)

[62, 6, 454, 52, 6, 130, 130, 959, 44, 46, 132, 46, 76, 499, 161, 528, 54]
[7, 628, 130, 144, 61, 1007, 73, 1025]
[46, 7, 89, 338, 952, 80, 13, 450, 254, 121]


In [37]:
# Lookup each token id in the vocabulary.
txt_tokens = tf.gather(fr_vocab, token_batch)
# Join with spaces.
tf.strings.reduce_join(txt_tokens, separator=' ', axis=-1)

<tf.Tensor: shape=(3,), dtype=string, numpy=
array([b'elle a eu un a ##c ##c ##ident de la route la se ##ma ##ine dernier ##e',
       b'b ##lan ##c comme du cafe au lait',
       b'la b ##a ##f ##fe ca h ##um ##il ##ie'], dtype=object)>

To re-assemble words from the extracted tokens, use the `BertTokenizer.detokenize` method:

In [38]:
words = fr_tokenizer.detokenize(token_batch)
tf.strings.reduce_join(words, separator=' ', axis=-1)

<tf.Tensor: shape=(3,), dtype=string, numpy=
array([b'elle a eu un accident de la route la semaine derniere',
       b'blanc comme du cafe au lait', b'la baffe ca humilie'],
      dtype=object)>

> Note: `BertTokenizer.tokenize`/`BertTokenizer.detokenize` does not round
trip losslessly. The result of `detokenize` will not, in general, have the
same content or offsets as the input to `tokenize`. This is because of the
"basic tokenization" step, that splits the strings into words before
applying the `WordpieceTokenizer`, includes irreversible
steps like lower-casing and splitting on punctuation. `WordpieceTokenizer`
on the other hand **is** reversible.

### Custom tokenization

The downstream tutorials both expect the tokenized text to include `[START]` and `[END]` tokens.

The `reserved_tokens` reserve space at the beginning of the vocabulary, so `[START]` and `[END]` have the same indexes for both languages:

In [39]:
START = tf.argmax(tf.constant(reserved_tokens) == "[START]")
END = tf.argmax(tf.constant(reserved_tokens) == "[END]")

def add_start_end(ragged):
  count = ragged.bounding_shape()[0]
  starts = tf.fill([count,1], START)
  ends = tf.fill([count,1], END)
  return tf.concat([starts, ragged, ends], axis=1)

In [40]:
words = fr_tokenizer.detokenize(add_start_end(token_batch))
tf.strings.reduce_join(words, separator=' ', axis=-1)

<tf.Tensor: shape=(3,), dtype=string, numpy=
array([b'[START] elle a eu un accident de la route la semaine derniere [END]',
       b'[START] blanc comme du cafe au lait [END]',
       b'[START] la baffe ca humilie [END]'], dtype=object)>

### Custom detokenization

Before exporting the tokenizers there are a couple of things you can cleanup for the downstream tutorials:

1. They want to generate clean text output, so drop reserved tokens like `[START]`, `[END]` and `[PAD]`.
2. They're interested in complete strings, so apply a string join along the `words` axis of the result.  

In [41]:
def cleanup_text(reserved_tokens, token_txt):
  # Drop the reserved tokens, except for "[UNK]".
  bad_tokens = [re.escape(tok) for tok in reserved_tokens if tok != "[UNK]"]
  bad_token_re = "|".join(bad_tokens)

  bad_cells = tf.strings.regex_full_match(token_txt, bad_token_re)
  result = tf.ragged.boolean_mask(token_txt, ~bad_cells)

  # Join them into strings.
  result = tf.strings.reduce_join(result, separator=' ', axis=-1)

  return result

In [42]:
fr_examples.numpy()

array([b'elle a eu un accident de la route la semaine derni\xc3\xa8re',
       b'blanc comme du caf\xc3\xa9 au lait',
       b'la baffe  \xc3\xa7a humilie'], dtype=object)

In [43]:
token_batch = fr_tokenizer.tokenize(fr_examples).merge_dims(-2,-1)
words = fr_tokenizer.detokenize(token_batch)
words

<tf.RaggedTensor [[b'elle', b'a', b'eu', b'un', b'accident', b'de', b'la', b'route', b'la',
  b'semaine', b'derniere']                                                ,
 [b'blanc', b'comme', b'du', b'cafe', b'au', b'lait'],
 [b'la', b'baffe', b'ca', b'humilie']]>

In [44]:
cleanup_text(reserved_tokens, words).numpy()

array([b'elle a eu un accident de la route la semaine derniere',
       b'blanc comme du cafe au lait', b'la baffe ca humilie'],
      dtype=object)

### Export

The following code block builds a `CustomTokenizer` class to contain the `text.BertTokenizer` instances, the custom logic, and the `@tf.function` wrappers required for export.

In [45]:
class CustomTokenizer(tf.Module):
  def __init__(self, reserved_tokens, vocab_path):
    self.tokenizer = text.BertTokenizer(vocab_path, lower_case=True)
    self._reserved_tokens = reserved_tokens
    self._vocab_path = tf.saved_model.Asset(vocab_path)

    vocab = pathlib.Path(vocab_path).read_text().splitlines()
    self.vocab = tf.Variable(vocab)

    ## Create the signatures for export:

    # Include a tokenize signature for a batch of strings.
    self.tokenize.get_concrete_function(
        tf.TensorSpec(shape=[None], dtype=tf.string))

    # Include `detokenize` and `lookup` signatures for:
    #   * `Tensors` with shapes [tokens] and [batch, tokens]
    #   * `RaggedTensors` with shape [batch, tokens]
    self.detokenize.get_concrete_function(
        tf.TensorSpec(shape=[None, None], dtype=tf.int64))
    self.detokenize.get_concrete_function(
          tf.RaggedTensorSpec(shape=[None, None], dtype=tf.int64))

    self.lookup.get_concrete_function(
        tf.TensorSpec(shape=[None, None], dtype=tf.int64))
    self.lookup.get_concrete_function(
          tf.RaggedTensorSpec(shape=[None, None], dtype=tf.int64))

    # These `get_*` methods take no arguments
    self.get_vocab_size.get_concrete_function()
    self.get_vocab_path.get_concrete_function()
    self.get_reserved_tokens.get_concrete_function()

  @tf.function
  def tokenize(self, strings):
    enc = self.tokenizer.tokenize(strings)
    # Merge the `word` and `word-piece` axes.
    enc = enc.merge_dims(-2,-1)
    enc = add_start_end(enc)
    return enc

  @tf.function
  def detokenize(self, tokenized):
    words = self.tokenizer.detokenize(tokenized)
    return cleanup_text(self._reserved_tokens, words)

  @tf.function
  def lookup(self, token_ids):
    return tf.gather(self.vocab, token_ids)

  @tf.function
  def get_vocab_size(self):
    return tf.shape(self.vocab)[0]

  @tf.function
  def get_vocab_path(self):
    return self._vocab_path

  @tf.function
  def get_reserved_tokens(self):
    return tf.constant(self._reserved_tokens)

Build a `CustomTokenizer` for each language:

In [46]:
tokenizers = tf.Module()
tokenizers.dyu = CustomTokenizer(reserved_tokens, 'dyu_vocab.txt')
tokenizers.fr = CustomTokenizer(reserved_tokens, 'fr_vocab.txt')

Export the tokenizers as a `saved_model`:

In [47]:
model_name = 'translate_dyula_french'
tf.saved_model.save(tokenizers, model_name)

Reload the `saved_model` and test the methods:

In [48]:
reloaded_tokenizers = tf.saved_model.load(model_name)
reloaded_tokenizers.fr.get_vocab_size().numpy()

1069

In [49]:
tokens = reloaded_tokenizers.fr.tokenize(['Bonjour TensorFlow!'])
tokens.numpy()

array([[   2,  243, 1054,  340,  251,  377,  410,  338,  967, 1056,    1,
           3]])

In [50]:
text_tokens = reloaded_tokenizers.fr.lookup(tokens)
text_tokens

<tf.RaggedTensor [[b'[START]', b'bon', b'##j', b'##our', b'te', b'##ns', b'##or', b'##f',
  b'##lo', b'##w', b'[UNK]', b'[END]']]>

In [52]:
round_trip = reloaded_tokenizers.fr.detokenize(tokens)

print(round_trip.numpy()[0].decode('utf-8'))

bonjour tensorflow [UNK]


Archive it for the [translation tutorials](https://tensorflow.org/text/tutorials/transformer):

In [53]:
!zip -r {model_name}.zip {model_name}

  adding: translate_dyula_french/ (stored 0%)
  adding: translate_dyula_french/assets/ (stored 0%)
  adding: translate_dyula_french/assets/fr_vocab.txt (deflated 53%)
  adding: translate_dyula_french/assets/dyu_vocab.txt (deflated 52%)
  adding: translate_dyula_french/saved_model.pb (deflated 91%)
  adding: translate_dyula_french/fingerprint.pb (stored 0%)
  adding: translate_dyula_french/variables/ (stored 0%)
  adding: translate_dyula_french/variables/variables.data-00000-of-00001 (deflated 49%)
  adding: translate_dyula_french/variables/variables.index (deflated 33%)


In [54]:
!du -h *.zip

272K	koumankan_mt_dyu_fr_tfds.zip
80K	translate_dyula_french.zip
